hostname: monitoring
ip_address: 192.168.1.51
gateway: 192.168.1.254
netmask: 255.255.255.0
dns_servers:
  - 192.168.1.254
  - 8.8.8.8

prom_version: "3.2.1"
node_exporter_version: "1.9.0"
basic_auth_user: "admin"
basic_auth_pass: "Azerty/123"
ssl_dir: "/etc/ssl/prometheus-grafana"

prometheus_config: |
  global:
    scrape_interval: 15s

  scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']

    - job_name: 'node_exporter'
      static_configs:
        - targets: ['localhost:9100']

    - job_name: 'windows_exporter'
      static_configs:
        - targets: ['192.168.119.200:9182']
